services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: QuanLyWebBanHoa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    name: laravel-11x_laravel

volumes:
  dbdata:
    name: laravel-11x_dbdata
